### ISSUE TITLE
KotlinNullPointerException for NonStop.getId

### ISSUE THREAD

**Issue by fc9734ygn** [s3r6/svg-non-stop#1]
I'm getting an exception and I have no clue what's wrong. Maybe you would have an idea? I know that the svgs were exported from Adobe Illustrator, also replaced paths with "..." in the c/p.

```
...\svg-non-stop-1.0\bin\svg-non-stop.bat ...\tutorial1.svg -v
Option Verbose is on.
Parsed file .../tutorial1.svg
Document contains 7 nodes.
Processing gradient node style
Processing gradient node linearGradient
Found linear gradient with stops, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linear gradient with stops, id linear-gradient-5
Processing gradient node linearGradient
Found linear gradient with stops, id linear-gradient-6
Processing gradient node linearGradient
Found linked gradient, id linear-gradient-5
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Processing gradient node linearGradient
Found linked gradient, id linear-gradient
Inserting stops into target gradients.
Inserting stops for id linear-gradient, 16 gradient(s) count
Exception in thread "main" kotlin.KotlinNullPointerException
        at NonStop.getId(NonStop.kt:86)
        at NonStop.processSvg(NonStop.kt:58)
        at NonStopKt.main(NonStop.kt:135)
```
The svg content here:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 0 368.52 368.49">
    <defs>
        <style>
            .cls-1{opacity:0.4;}.cls-2{fill:url(#linear-gradient);}.cls-13,.cls-16,.cls-19,.cls-22,.cls-3{opacity:0.1;}.cls-3{fill:url(#linear-gradient-2);}.cls-4{opacity:0.2;}.cls-5{fill:url(#linear-gradient-3);}.cls-6{fill:url(#linear-gradient-4);}.cls-7{fill:#252551;}.cls-8{fill:url(#linear-gradient-5);}.cls-9{fill:url(#linear-gradient-6);}.cls-10{fill:url(#linear-gradient-7);}.cls-11{fill:url(#linear-gradient-8);}.cls-12{fill:#fff;}.cls-13{fill:url(#linear-gradient-9);}.cls-14{fill:url(#linear-gradient-10);}.cls-15{fill:url(#linear-gradient-11);}.cls-16{fill:url(#linear-gradient-13);}.cls-17{fill:url(#linear-gradient-14);}.cls-18{fill:url(#linear-gradient-15);}.cls-19{fill:url(#linear-gradient-17);}.cls-20{fill:url(#linear-gradient-18);}.cls-21{fill:url(#linear-gradient-19);}.cls-22{fill:url(#linear-gradient-21);}.cls-23{fill:url(#linear-gradient-22);}.cls-24{fill:url(#linear-gradient-23);}
        </style>
        <linearGradient id="linear-gradient" x1="73.11" y1="72.17" x2="295.41" y2="296.33"
            gradientUnits="userSpaceOnUse">
            <stop offset="0" stop-color="#80a6f8" />
            <stop offset="1" stop-color="#4359f5" />
        </linearGradient>
        <linearGradient id="linear-gradient-2" x1="74.37" y1="73.44" x2="392.72" y2="394.45"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-3" x1="102.94" y1="102.25" x2="265.57" y2="266.24"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-4" x1="184.83" y1="242.51" x2="182.83" y2="38.33"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-5" x1="164.7" y1="169.99" x2="187.14" y2="209.9"
            gradientUnits="userSpaceOnUse">
            <stop offset="0" stop-color="#80a6f8" />
            <stop offset="1" stop-color="#fff" />
        </linearGradient>
        <linearGradient id="linear-gradient-6" x1="194.21" y1="198.22" x2="171.82" y2="207.7"
            gradientUnits="userSpaceOnUse">
            <stop offset="0" stop-color="#80a6f8" />
            <stop offset="1" stop-color="#fff" stop-opacity="0" />
        </linearGradient>
        <linearGradient id="linear-gradient-7" x1="172.45" y1="121.96" x2="185.98" y2="184.25"
            xlink:href="#linear-gradient-5" />
        <linearGradient id="linear-gradient-8" x1="180.91" y1="219.6" x2="235.41" y2="262.12"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-9" x1="126.12" y1="-44.11" x2="240.68" y2="100.41"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-10" x1="155.51" y1="26.91" x2="209.33" y2="26.91"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-11" x1="182.29" y1="46.75" x2="182.63" y2="-6.79"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-13" x1="126.12" y1="270.56" x2="240.68" y2="415.09"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-14" x1="155.51" y1="341.58" x2="209.33" y2="341.58"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-15" x1="182.29" y1="361.42" x2="182.63" y2="307.88"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-17" x1="285.31" y1="110.65" x2="399.87" y2="255.17"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-18" x1="314.7" y1="181.67" x2="368.52" y2="181.67"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-19" x1="341.48" y1="201.51" x2="341.82" y2="147.97"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-21" x1="-29.39" y1="112.62" x2="85.17" y2="257.15"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-22" x1="0" y1="183.64" x2="53.82" y2="183.64"
            xlink:href="#linear-gradient" />
        <linearGradient id="linear-gradient-23" x1="26.79" y1="203.48" x2="27.12" y2="149.94"
            xlink:href="#linear-gradient" />
    </defs>
    <title>tutorial1</title>
    <g id="Layer_2" data-name="Layer 2">
        <g id="Layer_1-2" data-name="Layer 1">
            <g class="cls-1">
                <path class="cls-2"
                    d="M184.33,342.1v-1c2,0,4,0,6-.12l0,1C188.37,342.06,186.33,342.1,184.33,342.1Zm-6.05-.12c-2-.07-4-.18-6-.33l.07-1c2,.15,4,.26,6,.34Zm18.13-.34-.08-1c2-.15,4-.34,6-.57l.12,1C200.43,341.29,198.41,341.48,196.41,341.64Zm-30.18-.56c-2-.23-4-.5-6-.8l.15-1c2,.3,4,.57,6,.79Zm42.19-.82-.15-1c2-.3,4-.65,5.92-1l.19,1C212.4,339.61,210.4,340,208.42,340.26Zm-54.14-1c-2-.37-4-.8-5.91-1.25l.22-1c1.95.46,3.93.88,5.88,1.25Zm66-1.29-.23-1c1.94-.45,3.9-.95,5.82-1.48l.27,1C224.21,337,222.24,337.51,220.29,338Zm-77.79-1.45c-1.93-.52-3.88-1.1-5.8-1.7l.3-1c1.91.6,3.85,1.17,5.77,1.7ZM232,334.76l-.3-.95c1.89-.6,3.81-1.25,5.69-1.92l.33.94C235.78,333.51,233.85,334.16,232,334.76Zm-101-1.89c-1.9-.68-3.8-1.4-5.67-2.16l.38-.92c1.85.74,3.74,1.46,5.62,2.14Zm112.36-2.2-.37-.92c1.83-.74,3.69-1.53,5.51-2.35l.41.91C247,329.13,245.17,329.93,243.32,330.67Zm-123.61-2.33c-1.83-.82-3.67-1.69-5.47-2.59l.44-.89c1.79.89,3.62,1.75,5.44,2.57Zm134.61-2.61-.44-.89c1.77-.88,3.56-1.81,5.32-2.77l.48.88C257.91,323.91,256.11,324.85,254.32,325.73ZM108.86,323c-1.75-.95-3.52-2-5.26-3l.52-.86c1.72,1,3.48,2,5.22,3Zm156.06-3-.51-.86c1.71-1,3.42-2.09,5.09-3.17l.55.84C268.37,317.86,266.64,318.93,264.92,320ZM98.46,316.77c-1.68-1.09-3.36-2.23-5-3.39l.58-.82c1.63,1.15,3.31,2.28,5,3.37Zm176.59-3.38-.58-.82c1.63-1.15,3.26-2.34,4.84-3.55l.61.8C278.33,311,276.69,312.23,275.05,313.39ZM88.57,309.8c-1.59-1.22-3.19-2.48-4.74-3.76l.64-.77c1.54,1.27,3.12,2.52,4.71,3.73Zm196.08-3.74-.63-.77c1.53-1.27,3.06-2.58,4.56-3.91l.66.75C287.74,303.46,286.2,304.79,284.65,306.06Zm-205.41-4c-1.5-1.34-3-2.73-4.43-4.11l.69-.72c1.43,1.38,2.91,2.75,4.41,4.08ZM293.68,298l-.7-.72c1.43-1.38,2.86-2.8,4.25-4.25l.72.7C296.55,295.2,295.12,296.64,293.68,298ZM70.53,293.71c-1.39-1.44-2.77-2.93-4.11-4.43l.75-.66c1.33,1.48,2.7,3,4.08,4.4Zm231.53-4.4-.74-.66c1.33-1.49,2.64-3,3.91-4.56l.77.63C304.73,286.27,303.4,287.82,302.06,289.31ZM62.49,284.7c-1.28-1.55-2.54-3.14-3.76-4.74l.79-.6c1.21,1.58,2.47,3.16,3.74,4.7ZM309.77,280l-.8-.61c1.21-1.59,2.41-3.22,3.56-4.84l.82.57C312.19,276.75,311,278.39,309.77,280Zm-254.61-4.9c-1.16-1.63-2.3-3.32-3.39-5l.84-.54c1.08,1.67,2.22,3.34,3.36,5Zm261.58-5-.84-.55c1.09-1.67,2.16-3.39,3.18-5.1l.86.51C318.91,266.68,317.84,268.41,316.74,270.1ZM48.58,265c-1-1.72-2-3.49-3-5.24l.88-.48c1,1.74,2,3.5,3,5.21Zm274.36-5.27-.88-.48c1-1.76,1.9-3.56,2.78-5.34l.9.45C324.85,256.12,323.91,257.93,322.94,259.7ZM42.8,254.37c-.89-1.8-1.76-3.63-2.58-5.45l.92-.41c.81,1.81,1.67,3.63,2.56,5.42Zm285.53-5.52-.92-.41c.83-1.84,1.62-3.7,2.36-5.54l.93.38C330,245.13,329.15,247,328.33,248.85ZM37.86,243.38c-.75-1.86-1.48-3.76-2.16-5.65l.94-.34c.68,1.88,1.4,3.77,2.14,5.61Zm295-5.77-.94-.34c.67-1.88,1.32-3.8,1.92-5.7l1,.3C334.19,233.78,333.54,235.72,332.86,237.61ZM33.76,232c-.61-1.91-1.18-3.86-1.72-5.8l1-.26c.53,1.92,1.1,3.86,1.7,5.76Zm302.75-5.93-1-.27c.53-1.93,1-3.89,1.48-5.82l1,.23C337.54,222.15,337,224.13,336.51,226.07Zm-306-5.73c-.45-1.94-.88-3.93-1.26-5.91l1-.19c.38,2,.81,3.94,1.26,5.88Zm308.7-6.05-1-.19c.38-2,.72-3.95,1-5.91l1,.15C340,210.31,339.63,212.31,339.25,214.29Zm-311-5.81c-.31-2-.58-4-.81-6l1-.11c.23,2,.5,4,.81,5.95Zm312.82-6.14-1-.11c.22-2,.41-4,.57-6l1,.08C341.5,198.33,341.31,200.36,341.08,202.34ZM26.87,196.47c-.15-2-.27-4-.34-6l1,0c.07,2,.19,4,.34,6ZM342,190.29l-1,0c.08-2,.12-4,.12-6V184h1v.27C342.11,186.25,342.07,188.29,342,190.29Zm-314.58-5.9h-1v-.14c0-2,0-3.95.11-5.91l1,0c-.08,2-.11,3.92-.11,5.87ZM341,178c-.08-2-.19-4-.35-6l1-.08c.15,2,.27,4,.35,6ZM27.85,172.38l-1-.07c.15-2,.34-4,.57-6l1,.11C28.19,168.39,28,170.4,27.85,172.38ZM340.06,166c-.23-2-.51-4-.81-6l1-.15c.3,2,.58,4,.81,6ZM29.2,160.44l-1-.15c.31-2,.65-4,1-5.95l1,.18C29.84,156.48,29.5,158.48,29.2,160.44Zm309-6.32c-.38-2-.81-3.94-1.26-5.88l1-.23c.46,2,.89,4,1.27,5.91ZM31.47,148.65l-1-.23c.45-1.95,1-3.92,1.48-5.86l1,.26C32.41,144.75,31.92,146.71,31.47,148.65Zm304-6.23c-.53-1.91-1.1-3.85-1.71-5.76l.95-.3c.61,1.92,1.19,3.87,1.72,5.8ZM34.63,137.06l-1-.3c.6-1.92,1.25-3.86,1.93-5.75l.94.34C35.88,133.23,35.23,135.15,34.63,137.06ZM331.83,131c-.68-1.88-1.4-3.77-2.15-5.62l.93-.37c.75,1.86,1.48,3.76,2.16,5.65ZM38.69,125.72l-.93-.37c.75-1.86,1.55-3.74,2.37-5.58l.92.41C40.23,122,39.44,123.87,38.69,125.72Zm288.63-5.86c-.82-1.82-1.68-3.64-2.56-5.42l.89-.44c.89,1.78,1.76,3.62,2.59,5.44Zm-283.7-5.13-.9-.44c.89-1.8,1.83-3.61,2.79-5.38l.88.48C45.43,111.15,44.5,112.94,43.62,114.73ZM322,109.13c-1-1.74-2-3.49-3-5.21l.86-.51c1,1.73,2,3.49,3,5.24Zm-272.61-5-.86-.51c1-1.73,2.1-3.46,3.19-5.14l.84.54C51.45,100.73,50.39,102.45,49.37,104.16Zm266.46-5.33c-1.09-1.67-2.22-3.35-3.37-5l.82-.57c1.15,1.63,2.29,3.31,3.39,5ZM55.91,94.07l-.82-.57c1.15-1.65,2.36-3.29,3.57-4.89l.8.61C58.25,90.81,57.05,92.44,55.91,94.07Zm253-5c-1.22-1.59-2.47-3.17-3.74-4.7l.77-.64c1.27,1.54,2.54,3.13,3.76,4.73ZM63.2,84.51l-.78-.63c1.27-1.55,2.6-3.09,3.94-4.6l.75.67C65.77,81.45,64.46,83,63.2,84.51Zm238.05-4.73c-1.32-1.48-2.69-3-4.08-4.41l.72-.69c1.4,1.45,2.78,2.94,4.11,4.43ZM71.19,75.54l-.72-.69c1.39-1.45,2.82-2.89,4.27-4.28l.69.72C74,72.67,72.57,74.1,71.19,75.54Zm221.73-4.41c-1.45-1.38-2.93-2.76-4.42-4.08l.67-.75c1.5,1.33,3,2.72,4.44,4.11ZM79.84,67.2l-.67-.74c1.49-1.33,3-2.66,4.59-3.94l.63.77C82.85,64.56,81.32,65.88,79.84,67.2Zm204.1-4.06c-1.54-1.27-3.13-2.53-4.71-3.73l.6-.8c1.6,1.22,3.19,2.48,4.75,3.76ZM89.09,59.56l-.6-.8c1.58-1.21,3.22-2.42,4.86-3.58l.58.82C92.3,57.15,90.67,58.35,89.09,59.56Zm185.29-3.71c-1.63-1.14-3.31-2.28-5-3.36l.55-.84c1.68,1.09,3.37,2.23,5,3.39ZM98.9,52.64l-.55-.84c1.68-1.09,3.4-2.17,5.13-3.19l.51.85C102.28,50.49,100.56,51.55,98.9,52.64Zm165.38-3.32c-1.71-1-3.47-2-5.23-3l.48-.87c1.77,1,3.54,2,5.26,3ZM109.2,46.49l-.48-.88c1.75-1,3.55-1.9,5.35-2.79l.44.9C112.73,44.6,110.94,45.54,109.2,46.49Zm144.51-2.92c-1.79-.88-3.63-1.75-5.45-2.56l.41-.91c1.83.81,3.68,1.68,5.48,2.58ZM119.93,41.15l-.41-.91c1.83-.82,3.69-1.62,5.55-2.37l.37.93C123.6,39.54,121.75,40.34,119.93,41.15Zm122.79-2.5c-1.85-.74-3.75-1.46-5.63-2.13l.34-.94c1.89.67,3.8,1.4,5.66,2.15Zm-111.67-2-.34-.94c1.88-.68,3.81-1.33,5.73-1.94l.3.95C134.84,35.33,132.92,36,131.05,36.65Zm100.33-2c-1.9-.6-3.84-1.17-5.76-1.69l.26-1c1.93.53,3.88,1.1,5.8,1.7ZM142.5,33l-.27-1c1.94-.53,3.92-1,5.86-1.49l.23,1C146.39,32,144.43,32.49,142.5,33Zm77.29-1.58c-1.94-.45-3.92-.87-5.88-1.24l.19-1c2,.38,4,.8,5.92,1.25ZM154.2,30.27l-.2-1c2-.38,4-.73,6-1l.15,1C158.15,29.55,156.16,29.89,154.2,30.27ZM208,29.18c-2-.3-4-.56-6-.79l.11-1c2,.22,4,.49,6,.79Zm-41.92-.74-.12-1c2-.23,4-.43,6-.58l.07,1C170.05,28,168,28.21,166.07,28.44Zm30-.61c-2-.14-4-.26-6-.33l0-1c2,.08,4,.19,6,.34Zm-18-.31,0-1c2-.08,4-.12,6.05-.12v1C182.05,27.4,180,27.44,178,27.52Z" />
            </g>
            <circle class="cls-3" cx="184.26" cy="184.25" r="115.03" />
            <g class="cls-4">
                <path class="cls-5"
                    d="M184.26,299.78A115.54,115.54,0,1,1,299.79,184.25,115.67,115.67,0,0,1,184.26,299.78Zm0-230.07A114.54,114.54,0,1,0,298.79,184.25,114.67,114.67,0,0,0,184.26,69.71Z" />
            </g>
            <circle class="cls-6" cx="184.26" cy="184.25" r="89.85" />
            <path class="cls-7"
                d="M247.72,247.85l-18.85-21.37a18.45,18.45,0,0,0-10.73-6l-21.73-3.68h-24.5l-25.13,6a18.39,18.39,0,0,0-10.14,6.46l-15.21,19.17a89.83,89.83,0,0,0,126.29-.62Z" />
            <path class="cls-8"
                d="M171.91,216.84c7.56,3.44,15.76,3.2,24.5,0-1.51-7.21-1.16-15.6,0-24.5h-24.5C172.65,199.72,173.25,207.25,171.91,216.84Z" />
            <path class="cls-9"
                d="M172.3,213.57a24.34,24.34,0,0,1,13.46-4.94c8.21-.44,6.66-10.75,6.66-10.75L172.55,200Z" />
            <path class="cls-10"
                d="M208.23,167.7H207V157.46a6.81,6.81,0,0,0-6.81-6.8H168.28a6.81,6.81,0,0,0-6.8,6.8V167.7h-2.72a3,3,0,0,0-3,3v3.94a5.25,5.25,0,0,0,5.25,5.25h.5v1.83c0,12.58,14.59,22.78,22.78,22.78S207,194.33,207,181.75v-1.93a5.26,5.26,0,0,0,4.22-5.15v-3.94A3,3,0,0,0,208.23,167.7Z" />
            <path class="cls-7"
                d="M161.88,169.2s-4.94-13-4-17.87l1.77,1s-2-12.08,4.77-13.74,21.84,5,34,1.33a10.32,10.32,0,0,1-4.31,4.76s11.1-3.4,13.76,4.91-1,21.59-1,21.59-3.6-14.19-9.59-13.36-17.95,4.32-24.69,2.91l4.78-3s-9.91-3.4-13.51,0C162.41,159.11,161.88,169.2,161.88,169.2Z" />
            <path class="cls-11"
                d="M219.24,244.49a6.43,6.43,0,1,0-10.05,5.31,3.87,3.87,0,0,1,7.24,0A6.41,6.41,0,0,0,219.24,244.49Z" />
            <path class="cls-12"
                d="M212.81,247.29a3.88,3.88,0,0,0-3.62,2.51,6.41,6.41,0,0,0,7.24,0A3.87,3.87,0,0,0,212.81,247.29Z" />
            <path class="cls-12"
                d="M215,244.24a6.19,6.19,0,0,1,.28-2.65,2.18,2.18,0,0,0-1.36.85,2.19,2.19,0,0,0-1.13-.32,2.24,2.24,0,0,0-1.12.31,2.26,2.26,0,0,0-1.37-.84,6.19,6.19,0,0,1,.28,2.65h0s0,.07,0,.1a2.21,2.21,0,1,0,4.42,0,.38.38,0,0,0,0-.1Z" />
            <circle class="cls-13" cx="182.42" cy="26.91" r="25.88" />
            <g class="cls-4">
                <path class="cls-14"
                    d="M182.42,53.82a26.91,26.91,0,1,1,26.91-26.91A26.94,26.94,0,0,1,182.42,53.82Zm0-52.82a25.91,25.91,0,1,0,25.91,25.91A25.94,25.94,0,0,0,182.42,1Z" />
            </g>
            <circle class="cls-15" cx="182.42" cy="26.91" r="18.34" />
            <path class="cls-15"
                d="M200.76,26.91a18.34,18.34,0,1,0-28.51,15.26c0-.13,0-.26,0-.4a10.19,10.19,0,0,1,20.37,0c0,.14,0,.27,0,.4A18.31,18.31,0,0,0,200.76,26.91Z" />
            <path class="cls-12"
                d="M182.42,31.59a10.19,10.19,0,0,0-10.19,10.18c0,.14,0,.27,0,.4a18.31,18.31,0,0,0,20.33,0c0-.13,0-.26,0-.4A10.18,10.18,0,0,0,182.42,31.59Z" />
            <circle class="cls-12" cx="182.42" cy="23.32" r="5.17" />
            <circle class="cls-16" cx="182.42" cy="341.58" r="25.88" />
            <g class="cls-4">
                <path class="cls-17"
                    d="M182.42,368.49a26.91,26.91,0,1,1,26.91-26.91A26.94,26.94,0,0,1,182.42,368.49Zm0-52.81a25.91,25.91,0,1,0,25.91,25.9A25.93,25.93,0,0,0,182.42,315.68Z" />
            </g>
            <circle class="cls-18" cx="182.42" cy="341.58" r="18.34" />
            <path class="cls-18"
                d="M200.76,341.58a18.34,18.34,0,1,0-28.51,15.27c0-.14,0-.27,0-.4a10.19,10.19,0,1,1,20.37,0c0,.13,0,.26,0,.4A18.33,18.33,0,0,0,200.76,341.58Z" />
            <path class="cls-12"
                d="M182.42,346.26a10.19,10.19,0,0,0-10.19,10.19c0,.13,0,.26,0,.4a18.36,18.36,0,0,0,20.33,0c0-.14,0-.27,0-.4A10.19,10.19,0,0,0,182.42,346.26Z" />
            <circle class="cls-12" cx="182.42" cy="337.99" r="5.17" />
            <circle class="cls-19" cx="341.61" cy="181.67" r="25.88" />
            <g class="cls-4">
                <path class="cls-20"
                    d="M341.61,208.58a26.91,26.91,0,1,1,26.91-26.91A26.94,26.94,0,0,1,341.61,208.58Zm0-52.82a25.91,25.91,0,1,0,25.91,25.91A25.94,25.94,0,0,0,341.61,155.76Z" />
            </g>
            <circle class="cls-21" cx="341.61" cy="181.67" r="18.34" />
            <path class="cls-21"
                d="M360,181.67a18.34,18.34,0,1,0-28.51,15.26c0-.13,0-.26,0-.4a10.19,10.19,0,0,1,20.37,0c0,.14,0,.27,0,.4A18.31,18.31,0,0,0,360,181.67Z" />
            <path class="cls-12"
                d="M341.61,186.35a10.19,10.19,0,0,0-10.19,10.18c0,.14,0,.27,0,.4a18.31,18.31,0,0,0,20.33,0c0-.13,0-.26,0-.4A10.18,10.18,0,0,0,341.61,186.35Z" />
            <circle class="cls-12" cx="341.61" cy="178.08" r="5.17" />
            <circle class="cls-22" cx="26.91" cy="183.64" r="25.88" />
            <g class="cls-4">
                <path class="cls-23"
                    d="M26.91,210.55a26.91,26.91,0,1,1,26.91-26.91A26.94,26.94,0,0,1,26.91,210.55Zm0-52.81a25.91,25.91,0,1,0,25.91,25.9A25.93,25.93,0,0,0,26.91,157.74Z" />
            </g>
            <circle class="cls-24" cx="26.91" cy="183.64" r="18.34" />
            <path class="cls-24"
                d="M45.25,183.64a18.34,18.34,0,1,0-28.51,15.27c0-.14,0-.27,0-.4a10.19,10.19,0,1,1,20.37,0c0,.13,0,.26,0,.4A18.33,18.33,0,0,0,45.25,183.64Z" />
            <path class="cls-12"
                d="M26.91,188.32a10.19,10.19,0,0,0-10.19,10.19c0,.13,0,.26,0,.4a18.36,18.36,0,0,0,20.33,0c0-.14,0-.27,0-.4A10.19,10.19,0,0,0,26.91,188.32Z" />
            <circle class="cls-12" cx="26.91" cy="180.05" r="5.17" />
        </g>
    </g>
</svg>
```

**Comment by s3r6** [comment]
There was no IDs on stops. Please check new release.
